### PR TITLE
fix issue #75

### PR DESCRIPTION
**Pull request by sdamasoc**
fix panasonic api changes adding missing headers

### CODE REVIEW

**Comment by hubert3** [comment]
Code in this PR is not working for me as of today 2023-09-21

```
[21/09/2023, 12:20:54] [Panasonic AC Platform] Comfort Cloud - login(): Error
[21/09/2023, 12:20:54] [Panasonic AC Platform] {
  "message": "Request failed with status code 400",
  "name": "AxiosError",
  "stack": "AxiosError: Request failed with status code 400\n    at settle (/usr/lib/node_modules/homebridge-panasonic-ac-platform/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessag
e.handleStreamEnd (/usr/lib/node_modules/homebridge-panasonic-ac-platform/node_modules/axios/lib/adapters/http.js:556:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (nod
e:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "config": {

```

Headers being sent:

```
  "headers": {
      "Accept": "application/json; charset=UTF-8",
      "Content-Type": "application/json",
      "User-Agent": "G-RAC",
      "X-APP-TYPE": "0",
      "X-APP-VERSION": "1.18.0",
      "Content-Length": "82",
      "Accept-Encoding": "gzip, compress, deflate, br"
    },
    "method": "post",
    "url": "https://accsmart.panasonic.com/auth/login",
```

**Comment by hubert3** [comment]
This PR fixes the plugin for me, working as of 2023-09-21

(Note for others wanting to apply the fix manually, you have to run tsc to compile comfort-cloud.ts to comfort-cloud.js)

**Review by amenff — APPROVED** [review]
Looks good. This should solve the new header issue. Credit goes to @mkz212

**Comment by miguelsasso** [comment]
Hi @embee8. Would be great if you could approve :)

**Review by efipso — APPROVED** [review]
This PR successfully fixes login issues

**Comment by miguelsasso** [comment]
This plugin was last updated 6 months ago and the last time the author made any contribution on github was 21 May 2023.  

I guess this plugin is essentially dead? 

I wonder if the author who owned the plugin upon which this fork is based, codyc1515, might be willing to take it back on...

**Comment by miguelsasso** [comment]
> This plugin was last updated 6 months ago and the last time the author made any contribution on github was 21 May 2023.
> 
> I guess this plugin is essentially dead?
> 
> I wonder if the author who owned the plugin upon which this fork is based, codyc1515, might be willing to take it back on...

I messaged him

**Comment by embee8** [comment]
Thank you all and apologies for the delay. This fix is part of the v1.6.1 release that just went out.

**Pull request closed without merging**
